### ISSUE TITLE
CVE in lodash.set

### ISSUE THREAD

**Issue by AnWeber** [gawsoftpl/grpc-js-reflection-api-client#8]
There is a CVE in lodash.set. Could you possibly switch to an alternative like `lodash` or `lodash-es` to fix this? 

see https://github.com/advisories/GHSA-p6mc-m468-83gw

```
lodash.set  *
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
```

https://github.com/gawsoftpl/grpc-js-reflection-api-client/blob/main/src/GrpcReflection.ts#L13

**Comment by gawsoftpl** [comment]
Fixed. I have changed package lodash.set to lodash. In few minutes will be release new package version.

**Comment by gawsoftpl** [comment]
Closed as fixed

**Comment by AnWeber** [comment]
Thx for the fast response
