### ISSUE TITLE
Possible to create descriptor set output from reflection that compatible to protoc 

### ISSUE THREAD

**Issue by the-duke** [gawsoftpl/grpc-js-reflection-api-client#9]
Hey dear devs! I like your project, it is very handy :-)
I try to create descriptor-set  .pb files from a server reflection. I would like it to be in the same format as the created output of the protoc with the option '--descriptor_set_out'.
I need the descriptor sets for the dynamic creation of envoy  config-handlers with the GrpcJsonTranscoder. This way I would like to expose an REST api for my grpc services.

i try this code.
```
const client = new GrpcReflection('0.0.0.0:60000', grpc.credentials.createInsecure());

 const protoDescriptor = await client.getProtoDescriptorBySymbol('ja.service_registry');
 const protoDescriptorBuffer = Buffer.concat(protoDescriptor);
 fs.writeFileSync('./ja_service_registry_registry.pb', protoDescriptorBuffer);

```

But the output code seems not to be correct. Envoy says  'Unable to parse proto descriptor'...

Do you have any hints for me?

Greetings

Thomas

**Comment by gawsoftpl** [comment]
I not sure that I understand, you want to create a proxy for proto descriptor?

**Comment by the-duke** [comment]
Hi! I want to create a proto-descriptor-set.pb files with jour lib from a given grpc-service and its reflection. I would like to create this descripor-set at runtime without having access to the proto files of the grpc-service. With this descripor-set.pb file i would like to feed a running evovy instance with a grpc-jso-tanscoder to make the api from the grpc-service accsessible via HTTP/JSON. (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto)

**Comment by gawsoftpl** [comment]
> Hi! I want to create a proto-descriptor-set.pb files with jour lib from a given grpc-service and its reflection. I would like to create this descripor-set at runtime without having access to the proto files of the grpc-service. With this descripor-set.pb file i would like to feed a running evovy instance with a grpc-jso-tanscoder to make the api from the grpc-service accsessible via HTTP/JSON. (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto)

I think that this will not possible, because protobuffer is send via reflection in binary mode not plain proto file. That's mean reflection send already parsed string "*proto" file and you want to share a plain string proto file. You have to find reverse eingeinering tools for parsed descriptor to string.
